name = "Visum"
author = "Horizr"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f3a4ccfdfdd28ebae7044e94d37ff9f962036b8bf81c262826861bd1cd8b75a"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
